import React from 'react'
import "./Policies.css"
const PrivacyPolicy = () => {
    return (
        <div className='PrivacyWapper'>
        <h2>Privacy Policy</h2>

        <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p><br></br>

        <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.</p><br></br>

        <h3>Interpretation and Definitions</h3>

        <h4>Interpretation</h4>

        <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p><br></br>

        <h4>Definitions</h4>

        <p>For the purposes of this Privacy Policy:</p>

           <ul className='Lists-Policies'>

            <li className='Lists-Policies'><span className='List-Policies-Bullets'>Account </span> means a unique account created for You to access our Service or parts of our Service.</li>

            <li className='Lists-Policies'><span className='List-Policies-Bullets'>Affiliate </span> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>

            <li className='Lists-Policies'><span className='List-Policies-Bullets'>Company </span>  (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Dhriti Silver LLP, 383B, Plot No. 39, Mangalmurti Jwell Palace, Shahupuri Chawk, Satara city, Satara, Maharashtra, 415002.</li>

            <li className='Lists-Policies'><span className='List-Policies-Bullets'>Cookies </span> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>

            <li className='Lists-Policies'><span className='List-Policies-Bullets'>Country </span> refers to: Maharashtra, India</li>

            <li className='Lists-Policies'><span className='List-Policies-Bullets'>Device </span> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>

            <li className='Lists-Policies'><span className='List-Policies-Bullets'>Personal Data </span> is any information that relates to an identified or identifiable individual.</li>

            <li className='Lists-Policies'><span className='List-Policies-Bullets'>Service </span> refers to the Website.</li>

            <li className='Lists-Policies'><span className='List-Policies-Bullets'>Service Provider </span> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>

            <li className='Lists-Policies'><span className='List-Policies-Bullets'>Usage Data </span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>

            <li className='Lists-Policies'><span className='List-Policies-Bullets'>Website </span> refers to BREA, accessible from <a href="https://brea.co.in/" className='Linkings'> https://brea.co.in/</a></li>

            <li className='Lists-Policies'><span className='List-Policies-Bullets'>You </span> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>

            </ul>

            <h3>Collecting and Using Your Personal Data</h3>
            <h4>Types of Data Collected</h4><br></br>
            <h4>Personal Data</h4><br></br>

            <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>

            <ul className='Lists-Policies'>

            <li className='Lists-Policies'>Email Address</li>
            <li className='Lists-Policies'>First name and last name</li>
            <li className='Lists-Policies'>Phone number</li>
            <li className='Lists-Policies'>Address, State, Province, ZIP/Postal code, City</li>
            <li className='Lists-Policies'>Usage Data</li>
            </ul><br></br>

            <h4>Usage Data</h4> <br></br>

            <p>Usage Data is collected automatically when using the Service.</p> <br></br>

            <p>Usage Data may include information such as Your Device’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p> <br></br>

            <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p> <br></br>

            <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p><br></br>

            <h4>Tracking Technologies and Cookies</h4> <br></br>
            <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p><br></br>

            <ul className='Lists-Policies'>

            <li className='Lists-Policies'><span className='List-Policies-Bullets'>Cookies or Browser Cookies: </span>A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>

           <li className='Lists-Policies'><span className='List-Policies-Bullets'>Web Beacons: </span>Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
            </ul> <br></br>

            <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies on the Privacy Policies website article.</p><br></br>

            <p>We use both Session and Persistent Cookies for the purposes set out below:</p><br></br>

            <ul className='Lists-Policies'>

            <li className='Lists-Policies'><span className='List-Policies-Bullets'>Necessary / Essential Cookies </span><br></br><br></br>
            <span>Type: Session Cookies</span><br></br><br></br>
            <span>Administered by: Us</span><br></br><br></br>
            <span>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</span><br></br>
            </li><br></br>

            <li className='Lists-Policies'><span className='List-Policies-Bullets'>Cookies Policy / Notice Acceptance Cookies </span><br></br><br></br>
            <span>Type: Persistent Cookies</span><br></br><br></br>
            <span>Administered by: Us</span><br></br><br></br>
            <span>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</span><br></br>
            </li><br></br>

            <li className='Lists-Policies'><span className='List-Policies-Bullets'>Functionality Cookies </span><br></br><br></br>
            <span>Type: Persistent Cookies</span><br></br><br></br>
            <span>Administered by: Us</span><br></br><br></br>
            <span>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</span><br></br>
            </li>

           
            </ul> <br></br>
            <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p><br></br>


        </div>
    )
}

export default PrivacyPolicy
